//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelRegistrationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int Id { get; set; }
        public int RoomId { get; set; }
        public int PersonId { get; set; }
        public System.DateTime BookedFrom { get; set; }
        public System.DateTime BookedTo { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Room Room { get; set; }
    }
}
